openapi: 3.0.3
info:
  title: API Meteora
  version: 1.0.0
  description: Produtos e categorias do e-commerce de roupas Meteora
  license:
    name: GPLv3
    url: https://www.gnu.org/licenses/gpl-3.0.html.en
paths:
  /categorias/:
    get:
      operationId: categorias_list
      parameters:
      - name: ordering
        required: false
        in: query
        description: Qual campo usar ao ordenar os resultados.
        schema:
          type: string
      - name: page
        required: false
        in: query
        description: Um número de página dentro do conjunto de resultados paginado.
        schema:
          type: integer
      - name: search
        required: false
        in: query
        description: Um termo de busca.
        schema:
          type: string
      tags:
      - categorias
      security:
      - cookieAuth: []
      - basicAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PaginatedCategoriaList'
          description: ''
    post:
      operationId: categorias_create
      tags:
      - categorias
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Categoria'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Categoria'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Categoria'
        required: true
      security:
      - cookieAuth: []
      - basicAuth: []
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Categoria'
          description: ''
  /categorias/{id}/:
    get:
      operationId: categorias_retrieve
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        description: Um valor inteiro único que identifica este categoria.
        required: true
      tags:
      - categorias
      security:
      - cookieAuth: []
      - basicAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Categoria'
          description: ''
    put:
      operationId: categorias_update
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        description: Um valor inteiro único que identifica este categoria.
        required: true
      tags:
      - categorias
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Categoria'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Categoria'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Categoria'
        required: true
      security:
      - cookieAuth: []
      - basicAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Categoria'
          description: ''
    patch:
      operationId: categorias_partial_update
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        description: Um valor inteiro único que identifica este categoria.
        required: true
      tags:
      - categorias
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PatchedCategoria'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/PatchedCategoria'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/PatchedCategoria'
      security:
      - cookieAuth: []
      - basicAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Categoria'
          description: ''
    delete:
      operationId: categorias_destroy
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        description: Um valor inteiro único que identifica este categoria.
        required: true
      tags:
      - categorias
      security:
      - cookieAuth: []
      - basicAuth: []
      responses:
        '204':
          description: No response body
  /produtos/:
    get:
      operationId: produtos_list
      parameters:
      - name: ordering
        required: false
        in: query
        description: Qual campo usar ao ordenar os resultados.
        schema:
          type: string
      - name: page
        required: false
        in: query
        description: Um número de página dentro do conjunto de resultados paginado.
        schema:
          type: integer
      - name: search
        required: false
        in: query
        description: Um termo de busca.
        schema:
          type: string
      tags:
      - produtos
      security:
      - cookieAuth: []
      - basicAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PaginatedProdutoList'
          description: ''
    post:
      operationId: produtos_create
      tags:
      - produtos
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Produto'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Produto'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Produto'
        required: true
      security:
      - cookieAuth: []
      - basicAuth: []
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Produto'
          description: ''
  /produtos/{id}/:
    get:
      operationId: produtos_retrieve
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        description: Um valor inteiro único que identifica este produto.
        required: true
      tags:
      - produtos
      security:
      - cookieAuth: []
      - basicAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Produto'
          description: ''
    put:
      operationId: produtos_update
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        description: Um valor inteiro único que identifica este produto.
        required: true
      tags:
      - produtos
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Produto'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Produto'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Produto'
        required: true
      security:
      - cookieAuth: []
      - basicAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Produto'
          description: ''
    patch:
      operationId: produtos_partial_update
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        description: Um valor inteiro único que identifica este produto.
        required: true
      tags:
      - produtos
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PatchedProduto'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/PatchedProduto'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/PatchedProduto'
      security:
      - cookieAuth: []
      - basicAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Produto'
          description: ''
    delete:
      operationId: produtos_destroy
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        description: Um valor inteiro único que identifica este produto.
        required: true
      tags:
      - produtos
      security:
      - cookieAuth: []
      - basicAuth: []
      responses:
        '204':
          description: No response body
components:
  schemas:
    Categoria:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        nome:
          type: string
          maxLength: 100
        descricao:
          type: string
          nullable: true
          title: Descrição
          maxLength: 500
        criado_em:
          type: string
          format: date-time
          readOnly: true
          title: Data de criação
        atualizado_em:
          type: string
          format: date-time
          readOnly: true
          title: Data de atualização
      required:
      - atualizado_em
      - criado_em
      - id
      - nome
    PaginatedCategoriaList:
      type: object
      required:
      - count
      - results
      properties:
        count:
          type: integer
          example: 123
        next:
          type: string
          nullable: true
          format: uri
          example: http://api.example.org/accounts/?page=4
        previous:
          type: string
          nullable: true
          format: uri
          example: http://api.example.org/accounts/?page=2
        results:
          type: array
          items:
            $ref: '#/components/schemas/Categoria'
    PaginatedProdutoList:
      type: object
      required:
      - count
      - results
      properties:
        count:
          type: integer
          example: 123
        next:
          type: string
          nullable: true
          format: uri
          example: http://api.example.org/accounts/?page=4
        previous:
          type: string
          nullable: true
          format: uri
          example: http://api.example.org/accounts/?page=2
        results:
          type: array
          items:
            $ref: '#/components/schemas/Produto'
    PatchedCategoria:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        nome:
          type: string
          maxLength: 100
        descricao:
          type: string
          nullable: true
          title: Descrição
          maxLength: 500
        criado_em:
          type: string
          format: date-time
          readOnly: true
          title: Data de criação
        atualizado_em:
          type: string
          format: date-time
          readOnly: true
          title: Data de atualização
    PatchedProduto:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        nome:
          type: string
          maxLength: 255
        descricao:
          type: string
          nullable: true
          title: Descrição
          maxLength: 1000
        preco:
          type: string
          format: decimal
          pattern: ^-?\d{0,3}(?:\.\d{0,2})?$
          title: Preço
        quantidade_estoque:
          type: integer
          maximum: 9223372036854775807
          minimum: 0
          format: int64
          title: Quantidade no estoque
        imagem:
          nullable: true
          oneOf:
          - type: string
            format: uri
          - type: string
            maxLength: 0
        criado_em:
          type: string
          format: date-time
          readOnly: true
          title: Data de criação
        atualizado_em:
          type: string
          format: date-time
          readOnly: true
          title: Data de atualização
        categoria:
          type: integer
    Produto:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        nome:
          type: string
          maxLength: 255
        descricao:
          type: string
          nullable: true
          title: Descrição
          maxLength: 1000
        preco:
          type: string
          format: decimal
          pattern: ^-?\d{0,3}(?:\.\d{0,2})?$
          title: Preço
        quantidade_estoque:
          type: integer
          maximum: 9223372036854775807
          minimum: 0
          format: int64
          title: Quantidade no estoque
        imagem:
          nullable: true
          oneOf:
          - type: string
            format: uri
          - type: string
            maxLength: 0
        criado_em:
          type: string
          format: date-time
          readOnly: true
          title: Data de criação
        atualizado_em:
          type: string
          format: date-time
          readOnly: true
          title: Data de atualização
        categoria:
          type: integer
      required:
      - atualizado_em
      - categoria
      - criado_em
      - id
      - nome
      - preco
      - quantidade_estoque
  securitySchemes:
    basicAuth:
      type: http
      scheme: basic
    cookieAuth:
      type: apiKey
      in: cookie
      name: sessionid
