# Generated by Django 6.1 on 2026-08-24 22:28

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
                ('descricao', models.TextField(blank=True, max_length=500, null=True, verbose_name='Descrição')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Data de criação')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Data de atualização')),
            ],
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('descricao', models.TextField(blank=True, max_length=1000, null=True, verbose_name='Descrição')),
                ('preco', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Preço')),
                ('quantidade_estoque', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Quantidade no estoque')),
                ('imagem', models.CharField(blank=True, null=True, validators=[django.core.validators.URLValidator()])),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Data de criação')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Data de atualização')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meteora.categoria')),
            ],
        ),
    ]
